# Generated by Django 4.2.3 on 2023-07-30 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Casablanca', 'Casablanca'), ('Fez', 'Fez'), ('Tangier', 'Tangier'), ('Marrakesh', 'Marrakesh'), ('Salé', 'Salé'), ('Meknes', 'Meknes'), ('Rabat', 'Rabat'), ('Oujda', 'Oujda'), ('Kenitra', 'Kenitra'), ('Agadir', 'Agadir'), ('Tetouan', 'Tetouan'), ('Temara', 'Temara'), ('Safi', 'Safi'), ('Mohammedia', 'Mohammedia'), ('Khouribga', 'Khouribga'), ('El Jadida', 'El Jadida'), ('Beni Mellal', 'Beni Mellal'), ('Aït Melloul', 'Aït Melloul'), ('Nador', 'Nador'), ('Dar Bouazza', 'Dar Bouazza'), ('Taza', 'Taza'), ('Settat', 'Settat'), ('Berrechid', 'Berrechid'), ('Khemisset', 'Khemisset'), ('Inezgane', 'Inezgane'), ('Ksar El Kebir', 'Ksar El Kebir'), ('Larache', 'Larache'), ('Guelmim', 'Guelmim'), ('Khenifra', 'Khenifra'), ('Berkane', 'Berkane'), ('Taourirt', 'Taourirt'), ('Bouskoura', 'Bouskoura'), ('Fquih Ben Salah', 'Fquih Ben Salah'), ('Dcheira El Jihadia', 'Dcheira El Jihadia'), ('Oued Zem', 'Oued Zem'), ('El Kelaa Des Sraghna', 'El Kelaa Des Sraghna'), ('Sidi Slimane', 'Sidi Slimane'), ('Errachidia', 'Errachidia'), ('Guercif', 'Guercif'), ('Oulad Teima', 'Oulad Teima'), ('Ben Guerir', 'Ben Guerir'), ('Tifelt', 'Tifelt'), ('Lqliaa', 'Lqliaa'), ('Taroudant', 'Taroudant'), ('Sefrou', 'Sefrou'), ('Essaouira', 'Essaouira'), ('Fnideq', 'Fnideq'), ('Sidi Kacem', 'Sidi Kacem'), ('Tiznit', 'Tiznit'), ('Tan-Tan', 'Tan-Tan'), ('Ouarzazate', 'Ouarzazate'), ('Souk El Arbaa', 'Souk El Arbaa'), ('Youssoufia', 'Youssoufia'), ('Lahraouyine', 'Lahraouyine'), ('Martil', 'Martil'), ('Ain Harrouda', 'Ain Harrouda'), ('Suq as-Sabt Awlad an-Nama', 'Suq as-Sabt Awlad an-Nama'), ('Skhirat', 'Skhirat'), ('Ouazzane', 'Ouazzane'), ('Benslimane', 'Benslimane'), ('Al Hoceima', 'Al Hoceima'), ('Beni Ansar', 'Beni Ansar'), ("M'diq", "M'diq"), ('Sidi Bennour', 'Sidi Bennour'), ('Midelt', 'Midelt'), ('Azrou', 'Azrou'), ('Drargua', 'Drargua')], max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('is_fork', models.BooleanField(blank=True, default=False)),
                ('price', models.FloatField(default=0.0)),
                ('size', models.FloatField(default=0.0)),
                ('tage', models.CharField(choices=[('1e', 'premier'), ('2e', 'deuxième'), ('3e', 'troisième'), ('4e', 'quatrième'), ('5e', 'cinquième'), ('6e', 'sixième')], max_length=50)),
                ('rooms', models.IntegerField(default=0)),
                ('bathroom', models.IntegerField(default=0)),
                ('kitchen', models.IntegerField(default=0)),
                ('image1', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
