# Generated by Django 4.2.3 on 2023-07-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='period',
            field=models.CharField(choices=[('DAY', 'jour'), ('MONTH', 'mois')], default='mois', max_length=50),
        ),
    ]
