# Generated by Django 4.2.3 on 2023-07-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appartement_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='bathroom',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='kitchen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='size',
            field=models.FloatField(default=0.0, help_text='size in M*M'),
        ),
    ]
