# Generated by Django 4.2.3 on 2023-07-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_appartement_bathroom_alter_appartement_kitchen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='image1',
            field=models.ImageField(upload_to='apt-images'),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='apt-images'),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='apt-images'),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='apt-images'),
        ),
    ]
