# Generated by Django 4.2.3 on 2023-08-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_appartement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='price',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
