# Generated by Django 4.2.3 on 2023-08-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appartement_created_at_alter_appartement_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='apt-images'),
        ),
    ]
