# Generated by Django 4.2.3 on 2023-08-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_appartement_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
