# Generated by Django 4.2.3 on 2023-08-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_appartement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='occupied',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='status',
            field=models.CharField(choices=[('Show', 'show'), ('Hide', 'hide')], default='Show', max_length=50, null=True),
        ),
    ]
