# Generated by Django 4.2.3 on 2023-08-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='image',
            field=models.ImageField(default='static/images/owner.jpg', upload_to='profile_images'),
        ),
    ]
