# Generated by Django 4.2.3 on 2023-08-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_renter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.renter'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='renter',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
